#!/bin/bash

clear
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m          ⇱ Muzaffer Şanlı ⇲          \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "# Debian 10 64 bit için                          #"
echo -e "# Ubuntu 18.04 & Ubuntu 20.04 64 bit için        #"
echo -e "# KVM ve VMWare sanallaştırmalı VPS için         #"
echo -e "# Anuybazoelk tarafından oluşturuldu             #"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m          ⇱ TEŞEKKÜRLER ⇲          \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "# RIDWAN MAĞAZASI                                #"
echo -e "# ARYABLITAR                                     #"
echo -e "# EMALIANI                                        #"
echo -e "# ABONELERİM                                       #"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
echo -e "\E[44;1;39m          ⇱ HEPSİBİRARADAVPN ONVAO.NET ⇲          \E[0m"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m${NC}"
